### ISSUE TITLE
Echo tutorial referenced but not present

### ISSUE THREAD

**Issue by tuohy** [roburio/miou#3]
The documentation has an unresolved reference to an "echo" page, see the "tutorial" link in this section:
https://roburio.github.io/miou/miou/Miou/index.html#daemon-and-orphan-tasks.

https://github.com/roburio/miou/blob/bb5029d1693cac23386c6f2cbce8c3ff879191d2/lib/miou.mli#L192

**Comment by dinosaure** [comment]
Yes, it's currently on my computer and I will add it as soon as I can. I will ping you when it's done 👍

**Comment by dinosaure** [comment]
The `echo` tutorial is avaiable [here](https://roburio.github.io/miou/miou/echo.html). Thanks for your patience.

**Comment by reynir** [comment]
Since the organization has been renamed the tutorial is now at https://robur-coop.github.io/miou/miou/echo.html

**Comment by dinosaure** [comment]
Fixed, thanks!
